FROM alpine:3.5
LABEL MAINTAINER="Greg Junge <gregnuj@gmail.com>"

COPY ./rootfs /

RUN apk add --update --no-cache bash openssh && \
  sed -i s/#PermitRootLogin.*/PermitRootLogin\ yes/ /etc/ssh/sshd_config  && \
  passwd -d root && \
  echo 'root:moonshine' | chpasswd && \
  addgroup -S gj8287 && \
  adduser -s /bin/bash -h /home/gj8287 -G gj8287 -S gj8287 && \
  chown -R gj8287:gj8287 /home/gj8287 && \
  chmod u+rwx /home/gj8287 && \
  chmod go+rx /home/gj8287 && \
  echo 'gj8287:*' | chpasswd 


ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]
EXPOSE 22
CMD ["/usr/sbin/sshd -D -e"]
